[package]
name = "pice"
version = "0.0.2"
authors = ["pchan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inflections = "1.1.1"
rand = "0.7"
sciter-rs = "*"
